title: PhotoSorter
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  PhotoSorter easily sort you picture by the dates they where taken,
  and if they don't have any date you can choose to sort them by
  size or resolution
baseurl: "/PhotoSorter" # the subpath of your site, e.g. /blog
url: "https://hallowf.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: HallowsLab
github_username:  hallowf

# Build settings
remote_theme: pmarsceill/just-the-docs
# just-the-docs settings
# encoding
encofing: utf-8

# theme settings
search_enabled: true
aux_links:
  "PhotoSorter on Github":
    - "github.com/hallowf/PhotoSorter"


# Google analytics
ga_tracking:

# Jekyll-multiple-languages plugin settings
languages: ["en", "pt"]
exclude_from_localizations: ["assets", "js", "imgs", "README.md"]
# fix for missing languages on main build
langs: ["en","pt"]

# SEO tag stuff
social:
  name: hallowf
  links:
    - https://www.facebook.com/Hallows.Tech.Lab/
    - https://www.instagram.com/hallowstechlab/

plugins:
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
